## 这里的配置属性只是基础配置，如需更多功能配置，请自行扩展
dubbo:
  application:
    name: dubbo-provider
  registry:
    address: 192.168.75.128:2181
    protocol: zookeeper

  protocol:
    name: dubbo
    port: 20882
    telnet:




server:
  port: 8081