## 这里的配置属性只是基础配置，如需更多功能配置，请自行扩展
dubbo:
  registry:
    address: zookeeper://192.168.75.128:2181
  application:
    name: consumer
  monitor:
    protocol: registry
  consumer:
    check: false

server:
  port: 8083
